/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/XeokitViewer copy.vue')['default']
    LeftPanel: typeof import('./src/components/LeftPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TomekXeokitViewer: typeof import('./src/components/TomekXeokitViewer.vue')['default']
    XeokitViewer: typeof import('./src/components/XeokitViewer.vue')['default']
    XeokitViewerJakub: typeof import('./src/components/XeokitViewerJakub.vue')['default']
  }
}
