MAKEFLAGS += --silent --keep-going


########################################################################################
####                                 NPM SCRIPTS                                    ####
########################################################################################
.PHONY: dev-frontend dev-models dev-db

dev-frontend:
	@pnpm run dev:frontend

dev-models:
	@pnpm run dev:server:models

dev-db:
	@pnpm run dev:server:db


