[package]
name = "pathfinder"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
colored = "2.1.0"
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
winit = "0.30.5"
